### ISSUE TITLE
Context Menu entries

### ISSUE THREAD

**Issue by MegaZeroX10** [TobiasFaller/VHDTool#7]
It would be nice if it had a command line option called install/uninstall that adds/removes context menu entries to VHD(x) files named Mount/Unmount (which run it with no window and run the proper command on the VHD(x)).

**Comment by TobiasFaller** [comment]
How about using a set of .bat files? The installation / uninstallation might not be required that often and the installation of a shell context menu item with reg.exe does not seem that hard.

**Comment by MegaZeroX10** [comment]
How would they be able to determine the location where VHDTool.exe is located? I was thinking of the install and uninstall command parameters being made to call reg.exe with the proper parameters.

**Comment by TobiasFaller** [comment]
@MegaZeroX10 The batch files assume that the VHDTool.exe tool is located in the same folder as the batch files.
I plan on packing the tool with both batch files into a ZIP-file and to distribute them as a bundle.
Then this assumption should hold true in most cases.
