### ISSUE TITLE
Fix some of Vhd2Disk's issues

### ISSUE THREAD

**Issue by Zero3K** [TobiasFaller/VHDTool#8]
It would be nice if you could do that. The list of them is available at https://github.com/wooxo/Vhd2Disk/issues.

**Comment by TobiasFaller** [comment]
Unfortunately I have currently no time for that. I will leave this issue opened just in case some other person has some spare time and motivation.

**Comment by Zero3K** [comment]
I don't think anyone who visits this repository is interested in it. I hope to be proven wrong though.

**Comment by Zero3K** [comment]
Bump

**Comment by TobiasFaller** [comment]
@Zero3K This is not a forum to gain developers for another project. Please refrain from actively influencing the order of issues. I was already kind enough to leave this issue open even though it has nothing to do with this repository.
However, I'll close it now as there doesn't seem to be any interest.

If you are that interested in the other project then I would suppose get started learning about the internals and doing the changes yourself.

Best Regards,
Tobias Faller
