### ISSUE TITLE
Reduce size of VHDTool's exe

### ISSUE THREAD

**Issue by Zero3K** [TobiasFaller/VHDTool#9]
Why is it around 6 MB in size? It would be nice if it could be reduced to be around 200-600 KB if possible.

**Comment by TobiasFaller** [comment]
1. The executable is not stripped. (I might fix this sometime)
2. It's statically linked and therefore the size is not as small as when using only dynamic libraries.

However, a 6 MB file size should be no problem for a system which is able to run Windows.
